name: Build electron packages

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        # --frozen-lockfile doesn't allow installing anything not in the lockfile
        # --network-timeout is needed to download large dependendies
        run: yarn install --frozen-lockfile --network-timeout 600000
      - node: Run ESLint
        run: yarn lint
      - name: Check for unused imports
        run: yarn unused-exports
      - name: Build the package
        run: yarn make-zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: out/make/zip/**/*.zip
          retention-days: 5

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: packages
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: packages/**/.zip
